source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false
gem 'faker'

gem "rack-cors", "~> 2.0"
gem 'rspec'
gem 'byebug'
gem 'rails-i18n'

gem "dotenv-rails", "2.8.1"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "pg", "~> 1.1"
  gem "rubocop"
  gem "bundler-audit"
  gem 'ruby_audit'
  gem "brakeman"
end

gem "active_model_serializers", "~> 0.10.14"